#include <msp430.h>

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

#ifdef LOGIC
#define LOG(...)
#define PRINTF(...)
#define BLOCK_PRINTF(...)
#define BLOCK_PRINTF_BEGIN(...)
#define BLOCK_PRINTF_END(...)
#define INIT_CONSOLE(...)
#else
#include <libio/console.h>
#endif
#include <libmsp/mem.h>
#include <libmsp/periph.h>
#include <libmsp/clock.h>
#include <libmsp/watchdog.h>
#include <libmsp/gpio.h>
#include <libcapybara/capybara.h>
#include <libcapybara/power.h>
#include <libjit/jit.h>
#include <libmspdriver/driverlib.h>

#include "pins.h"
#define CONT_POWER 0
#define QUICKRECALL 0
#define SW 1
// Clang complains about too large array.
// For recursive, over 6250 has a problem so let's not make it too large
#define ARR_SIZE 5000
//#define ARR_SIZE 50000
#define LOG(...)

void init();
volatile __attribute__((section(".upper.nv_vars"))) int data_src[ARR_SIZE] = {
#include "./src.txt"
};
volatile __attribute__((section(".upper.nv_vars"))) int data_dst[ARR_SIZE];

__atomic__<size> safe_dma_transfer(__output__[size << 1] int* dst, __input__[size << 1] int* src, unsigned size) {
	__asm__ volatile ("MOVX.A R13, %0":"=m"(DMA1SA));
	__asm__ volatile ("MOVX.A R12, %0":"=m"(DMA1DA));
	// size in word
	DMA1SZ = size;
	uint16_t interruptState = __get_interrupt_state();
	__disable_interrupt();
	DMA1CTL |= (DMADT_1 | DMASRCINCR_3 | DMADSTINCR_3 | DMAEN | DMAREQ | DMAIE);
	__bis_SR_register(GIE + LPM0_bits); 
	__set_interrupt_state(interruptState);
	__scaling_rule__ {
		safe_dma_transfer(dst, src, size >> 1);
		safe_dma_transfer(dst + (size >> 1), src + (size >> 1), size >> 1);
	} __scaling_rule__
}
//void test_dma_transfer(int* dst, int* src, unsigned size) {
//	IF_ATOMIC(KNOB(size, 50000));
//	DMA1SA = src; // tmp
//	DMA1DA = dst;
//	__asm__ volatile ("MOVX.A R13, %0":"=m"(DMA1SA));
//	__asm__ volatile ("MOVX.A R12, %0":"=m"(DMA1DA));
//	// size in word
//	DMA1SZ = size;
//	uint16_t interruptState = __get_interrupt_state();
//	__disable_interrupt();
//	DMA1CTL |= (DMADT_1 | DMASRCINCR_3 | DMADSTINCR_3 | DMAEN | DMAREQ | DMAIE);
//	__bis_SR_register(GIE + LPM0_bits); 
//	__set_interrupt_state(interruptState);
//	ELSE();
//	safe_dma_transfer(dst, src, size >> 1);
//	safe_dma_transfer(dst + (size >> 1), src + (size >> 1), size >> 1);
//	END_IF();
//}
/*
	 void safe_dma_transfer(int* dst, int* src, unsigned size) {
	 IF_ATOMIC(KNOB(size, 50000));
	 __asm__ volatile ("MOVX.A R13, %0":"=m"(DMA1SA));
	 __asm__ volatile ("MOVX.A R12, %0":"=m"(DMA1DA));
// size in word
DMA1SZ = size;
uint16_t interruptState = __get_interrupt_state();
__disable_interrupt();
DMA1CTL |= (DMADT_1 | DMASRCINCR_3 | DMADSTINCR_3 | DMAEN | DMAREQ | DMAIE);
__bis_SR_register(GIE + LPM0_bits); 
__set_interrupt_state(interruptState);
ELSE();
safe_dma_transfer(dst, src, size >> 1);
safe_dma_transfer(dst + (size >> 1), src + (size >> 1), size >> 1);
END_IF();
}

void safe_dma_transfer(int* dst, int* src, unsigned size) {
IN(src, 0, size << 1);
OUT(dst, 0, size << 1);
PARAM(size);
SCALING_RULE_BEGIN();
safe_dma_transfer(dst, src, size >> 1);
safe_dma_transfer(dst + (size >> 1), src + (size >> 1), size >> 1);
SCALING_RULE_END();

__asm__ volatile ("MOVX.A R13, %0":"=m"(DMA1SA));
__asm__ volatile ("MOVX.A R12, %0":"=m"(DMA1DA));
// size in word
DMA1SZ = size;
uint16_t interruptState = __get_interrupt_state();
__disable_interrupt();
DMA1CTL |= (DMADT_1 | DMASRCINCR_3 | DMADSTINCR_3 | DMAEN | DMAREQ | DMAIE);
__bis_SR_register(GIE + LPM0_bits); 
__set_interrupt_state(interruptState);
}
 */

void dma_sw(int* dst, int* src, size_t size) {
	for (size_t i = 0; i < size; ++i)
		*(dst+i) = *(src+i);
}

// this should be generated by the compiler
int main()
{
	PROTECT_BEGIN();
	capybara_config_banks(0x0);
	PROTECT_END();

	while (1) {
		// memset cannot handle too large data (size overflow)
		//memset(&data_dst[0], 0, ARR_SIZE*sizeof(data_dst[0]));
		// for simple test only,
		data_dst[ARR_SIZE - 1] = 7;
		//data_src2[ARR_SIZE - 1] = 8;

#ifdef LOGIC
		GPIO(PORT_DBG, OUT) |= BIT(PIN_AUX_0);
		GPIO(PORT_DBG, OUT) &= ~BIT(PIN_AUX_0);
#else
		PROTECT_BEGIN();
		PRINTF("start %u\r\n", data_dst[ARR_SIZE - 1]);
		PROTECT_END();
#endif

#if QUICKRECALL == 1
		dma_transfer(&data_dst[0], &data_src[0], ARR_SIZE);	
#elif SW == 1
		dma_sw(&data_dst[0], &data_src[0], ARR_SIZE);
#else
		safe_dma_transfer(&data_dst[0], &data_src[0], ARR_SIZE);
#endif

#ifdef LOGIC
		GPIO(PORT_DBG, OUT) |= BIT(PIN_AUX_2);
		GPIO(PORT_DBG, OUT) &= ~BIT(PIN_AUX_2);
#else
		PROTECT_BEGIN();
		PRINTF("end %u\r\n", data_dst[ARR_SIZE-1]);
		PROTECT_END();
#endif
	}
	return 0;

}

void __attribute__((interrupt(DMA_VECTOR)))dmaIsrHandler(void) {
	if (DMA1CTL & DMAIFG)
		DMA1CTL &= ~DMAIFG;
	__bic_SR_register_on_exit(LPM0_bits);
}

void init()
{
	msp_watchdog_disable();
	msp_gpio_unlock();
	__enable_interrupt();
	capybara_wait_for_supply();
	capybara_config_pins();
	msp_clock_setup();

#if CONT_POWER == 0
	cb_rc_t deep_discharge_status = capybara_shutdown_on_deep_discharge();
	if (deep_discharge_status == CB_ERROR_ALREADY_DEEPLY_DISCHARGED)
		capybara_shutdown();
#endif

	INIT_CONSOLE();
	//GPIO(PORT_DBG, OUT) &= ~BIT(PIN_DBG0);
	//GPIO(PORT_DBG, DIR) |= BIT(PIN_DBG0);
#ifdef LOGIC
	GPIO(PORT_DBG, OUT) &= ~BIT(PIN_AUX_0);
	GPIO(PORT_DBG, OUT) &= ~BIT(PIN_AUX_1);
	GPIO(PORT_DBG, OUT) &= ~BIT(PIN_AUX_2);
	//GPIO(PORT_DBG, OUT) &= ~BIT(PIN_DBG0);

	GPIO(PORT_DBG, DIR) |= BIT(PIN_AUX_0);
	GPIO(PORT_DBG, DIR) |= BIT(PIN_AUX_1);
	GPIO(PORT_DBG, DIR) |= BIT(PIN_AUX_2);
	//GPIO(PORT_DBG, DIR) |= BIT(PIN_DBG0);

	GPIO(PORT_DBG, OUT) |= BIT(PIN_AUX_1);
	GPIO(PORT_DBG, OUT) &= ~BIT(PIN_AUX_1);
#else
	unsigned pc;
	__asm__ volatile ("MOV &0x4400, %0":"=m"(pc));
	PRINTF(".%x.%u\r\n", pc, _jit_0_size);
#endif
}
