# Available configuration variables for the library and their default values.
# To change a value, override the variable in the application makefile, not here.

# Model of the temperature sensor. Supported models: tmp36
LIBTEMP_SENSOR ?= tmp36

# ADC channel number to which the sensor output is wired
LIBTEMP_ADC_CHAN ?=
